/* size */
#define LEN 1024
/* type */
/** conjugator **/
#define CjType_C 1
#define CjType_AA 2
#define CjType_AD 3
#define CjType_DD 4 
#define CjType_DA 5 
/** node **/
#define NdType_Dict 1
#define NdType_Arr 2
#define NdType_KV 4
#define NdType_Key 8
#define NdType_Val 16
