#!/bin/bash
## declare, allocate, assign
sym=$1
declare -a ldarray=()
declare -a syarray=()

## arguments, help
if [[ $sym == '-h' ]]; then
  echo 'USAGE:'
  echo ' search_sym -h'
  echo '  : prints help.'
  echo ' search_sym.bash <symbol>'
  echo '  : search symbol form ldconfig, /usr/local/lib/blas, /usr/local/lib/lapack.'
  echo 'STATUS:'
  echo ' Under constrution.'
  echo '  implemented : for ldconfig.'
  echo '  implemented : for blas.'
  exit
fi

## earch /usr/local/lib/lapack
src="/usr/local/lib/lapack"
echo "Search: ${src}"
ldarray=`find $src | grep -e \.a$ -e \.o$ -e \.so$`
for e in ${ldarray[@]}; do
  #echo :::${e}:::
  syarray=`nm ${e} | grep -i $sym`
  IFS=$'\n'
  for s in ${syarray}; do
    echo ${e}::: ${s}
  done
done

## earch /usr/local/lib/blas
src="/usr/local/lib/blas"
echo "Search: ${src}"
ldarray=`find $src | grep -e \.a$ -e \.o$ -e \.so$`
for e in ${ldarray[@]}; do
  #echo :::${e}:::
  syarray=`nm ${e} | grep -i $sym`
  IFS=$'\n'
  for s in ${syarray}; do
    echo ${e}::: ${s}
  done
done

## search ldconfig
src="ldconfig"
echo "Search: ${src}"
ldarray=`ldconfig  -p | awk -F' => ' '{print $2}'`
for e in ${ldarray[@]}; do
  #echo :::${e}:::
  syarray=`nm ${e} | grep -i $sym`
  IFS=$'\n'
  for s in ${syarray}; do
    echo ${e}::: ${s}
  done
done

