#!/bin/bash
## declare, allocate, assign
sym=$1
declare -a ldarray=()
declare -a syarray=()

## arguments
if [[ $sym == '-h' ]]; then
  echo 'USAGE:'
  echo ' search_sym.bash -h'
  echo '  : prints help.'
  echo ' search_sym.bash <symbol>'
  echo '  : search symbol form ldconfig, /usr/local/lib/blas, /usr/local/lib/lapack.'
  echo 'STATUS:'
  echo ' Under constrution.'
  echo ' implemented : for ldconfig'
  exit
fi

## search ldconfig
src="ldconfig"
echo $src
ldarray=`ldconfig  -p | awk -F' => ' '{print $2}'`
for e in ${ldarray[@]}; do
  #echo :::${e}:::
  syarray=`nm ${e} | grep $sym`
    IFS=$'\n'
    for s in ${syarray}; do
      echo ${e}::: ${s}
    done
done

