#!/bin/bash
## declare, allocate, assign
sym=$1
dir=$2
declare -a ldarray=()
declare -a syarray=()

## arguments, help
if [[ $sym == '-h' || $# -eq 0 ]]; then
  echo 'USAGE:'
  echo ' search_sym_d -h'
  echo '  : prints help.'
  echo ' search_sym_d <symbol> <directory>'
  echo '  : search <symbol> from files *.o, *.so and *.a in <directory>'
  echo 'STATUS:'
  echo ' complete.'
  exit
fi

## search
src=$dir
echo "Search: ${src}"
ldarray=`find $src | grep -e \.a$ -e \.o$ -e \.so$`
for e in ${ldarray[@]}; do
  #echo :::${e}:::
  syarray=`nm ${e} | grep -i $sym`
  IFS=$'\n'
  for s in ${syarray}; do
    echo ${e}::: ${s}
  done
done

