#!/bin/bash
# this is a tq meta command
# Needs: tq.o , tqR2D.pl , tqD2F.pl
# {.tgt , .ddf , .dsz , .ddl} =cat=> .frl =perl=> frl.dry =perl=> frl.dry.fed =perl=> .frl.dry.fed.com
if [ $# -eq 0 ]; then
  echo "Usage:"
  echo "  tq target=<file>"
  exit;
fi

array=$@

if [ $1 = "-B" ]; then
  ./tq.o ${array#-B}
  exit;
elif [ $1 = "-P" ]; then
  ./tqR2D.pl ${array#-P}
  exit;
else
  tgt=${1#target=}
fi


## create FRL
if [ -e $tgt ]; then
  echo "Target file:"
  echo "  $tgt"
  echo "  ${tgt}.tgt"
  echo "  ${tgt}.dsz"
  echo "  ${tgt}.ddf"
  echo "  ${tgt}.ddl"
  cat ${tgt}.ddl ${tgt}.ddf ${tgt}.dsz ${tgt}.tgt > ${tgt}.frl
  echo "Create ${tgt}.frl"
else
  echo "no target file"
  exit;
fi

## FRL => DRY
echo "Create ${tgt}.frl.dry , ${tgt}.frl.dry.fed.com"
./tqR2D.pl ${tgt}.frl > ${tgt}.frl.dry
## DRY => FED
echo "Create ${tgt}.frl.dry.fed"
./tqD2F.pl ${tgt}.frl.dry # => toSheet.dry.fed
## FED => EXEC
## EXEC
chmod 755 ./${tgt}.frl.dry.fed.com
./${tgt}.frl.dry.fed.com


